Repository informatici/openhospital-ui, pull requests merged in 2020-10, with the labels that each got.

#42 OP-304 | Fix PatientDetailsActivity responsiveness
  src/assets/arrow.svg
  src/components/activities/patientDetailsActivity/PatientDetailsActivity.tsx
  src/components/activities/patientDetailsActivity/styles.scss
Labels: enhancement

#43 OP-302 | Fix NewPatientActivity responsiveness
  src/assets/profile.svg
  src/components/accessories/patientDataForm/PatientDataForm.tsx
  src/components/accessories/patientDataForm/styles.scss
  src/components/activities/newPatientActivity/NewPatientActivity.tsx
  src/components/activities/newPatientActivity/styles.scss
Labels: enhancement

#45 OP-297 | Resolve preloaded picture and set it as default
  src/assets/example.jpeg
  src/components/accessories/profilePicture/ProfilePicture.tsx
  src/components/accessories/profilePicture/utils.ts
Labels: good first issue

#48 OP-289 | New patient submit
  src/assets/check-icon.png
  src/assets/fail-icon.png
  src/components/accessories/button/Button.tsx
  src/components/accessories/button/types.ts
  src/components/accessories/confirmationDialog/ConfirmationDialog.tsx
  src/components/accessories/confirmationDialog/styles.scss
  src/components/accessories/confirmationDialog/types.ts
  src/components/accessories/patientDataForm/PatientDataForm.tsx
  src/components/accessories/patientDataForm/types.ts
  src/components/accessories/profilePicture/ProfilePicture.tsx
  src/components/accessories/profilePicture/types.ts
  src/components/accessories/profilePicture/utils.ts
  src/components/accessories/smallButton/SmallButton.tsx
  src/components/accessories/smallButton/types.ts
  src/components/accessories/textButton/TextButton.tsx
  src/components/accessories/textButton/types.ts
  src/components/activities/loginActivity/LoginActivity.tsx
  src/components/activities/newPatientActivity/NewPatientActivity.tsx
  src/components/activities/newPatientActivity/styles.scss
  src/components/activities/newPatientActivity/types.ts
  src/state/patients/initial.ts
  src/state/patients/reducer.ts
  src/state/types.ts
  src/styles/_variables.scss
Labels: enhancement, good first issue

#49 Feature/change authentication
  api/oh.yaml
  src/components/activities/dashboardActivity/DashboardActivity.tsx
  src/components/activities/dashboardActivity/types.ts
  src/components/activities/loginActivity/types.ts
  src/components/activities/newPatientActivity/NewPatientActivity.tsx
  src/components/activities/patientDetailsActivity/PatientDetailsActivity.tsx
  src/components/activities/searchPatientActivity/SearchPatientActivity.tsx
  src/generated/apis/DeliveryTypeControllerApi.ts
  src/generated/apis/ExamControllerApi.ts
  src/generated/apis/LoginApiApi.ts
  src/generated/apis/ReportsControllerApi.ts
  src/generated/apis/VaccineControllerApi.ts
  src/generated/apis/WardControllerApi.ts
  src/generated/models/LoginResponse.ts
  src/generated/models/PatientDTO.ts
  src/generated/models/Resource.ts
  src/generated/models/index.ts
  src/state/main/actions.ts
  src/state/main/types.ts
Labels: dependencies

#52 OP-296 | Create env.staging and add build script
  .env.staging
  package-lock.json
  package.json
Labels: dependencies

#47 OP-236 | Mock search patient API call
  src/components/activities/searchPatientActivity/PatientSearchItem.tsx
  src/components/activities/searchPatientActivity/SearchPatientActivity.tsx
  src/components/activities/searchPatientActivity/styles.scss
  src/components/activities/searchPatientActivity/types.ts
  src/libraries/uiUtils/handleScrollToElement.ts
  src/server.js
  src/state/patients/actions.ts
  src/state/patients/consts.ts
  src/state/patients/initial.ts
  src/state/patients/reducer.ts
  src/state/types.ts
  src/styles/_variables.scss
Labels: good first issue

#46 OP-301 Add Dashboard to nav menu
  src/components/accessories/appHeader/AppHeader.tsx
  src/components/accessories/appHeader/styles.scss
Labels: good first issue

#54 OP-318 | Fix app routing
  cypress/integration/login_activity_spec.js
  src/App.tsx
  src/Routes.tsx
  src/components/accessories/appHeader/AppHeader.tsx
  src/components/accessories/privateRoute/PrivateRoute.tsx
  src/components/activities/dashboardActivity/DashboardActivity.tsx
  src/components/activities/dashboardActivity/types.ts
  src/components/activities/loginActivity/LoginActivity.tsx
  src/components/activities/loginActivity/types.ts
  src/components/activities/newPatientActivity/NewPatientActivity.tsx
  src/components/activities/newPatientActivity/types.ts
  src/components/activities/searchPatientActivity/PatientSearchItem.tsx
  src/components/activities/searchPatientActivity/types.ts
  src/libraries/authUtils/isAuthenticated.ts
  src/state/main/actions.ts
  src/state/main/consts.ts
  src/state/main/reducer.ts
  src/types.ts
Labels: bug

#58 OP-324 | Search patient activity
  cypress/integration/search_patient_activity_spec.js
  package-lock.json
  package.json
  src/components/accessories/textField/TextField.tsx
  src/components/accessories/textField/types.ts
  src/components/activities/searchPatientActivity/PatientSearchItem.tsx
  src/components/activities/searchPatientActivity/SearchPatientActivity.tsx
  src/components/activities/searchPatientActivity/styles.scss
  src/index.tsx
  src/mockServer/fixtures/patientDTO.js
  src/mockServer/server.js
  src/server.js
  src/state/patients/actions.ts
Labels: enhancement

#57 OP-313 | Pass down callback to reset form
  cypress/integration/new_patient_activity_spec.js
  src/components/accessories/patientDataForm/PatientDataForm.tsx
  src/components/accessories/patientDataForm/types.ts
  src/components/accessories/profilePicture/ProfilePicture.tsx
  src/components/accessories/profilePicture/types.ts
  src/components/activities/newPatientActivity/NewPatientActivity.tsx
  src/components/activities/newPatientActivity/consts.ts
  src/mockServer/server.js
  src/state/patients/reducer.ts
Labels: enhancement
