Repository informatici/openhospital-ui, pull requests merged in 2022-04, with the labels that each got.

#259 OP-804 | Mark required fields
  src/components/accessories/dateField/DateField.tsx
  src/components/accessories/dateField/types.ts
  src/components/accessories/patientDataForm/PatientDataForm.tsx
  src/components/accessories/selectField/SelectField.tsx
  src/components/accessories/selectField/types.ts
  src/components/accessories/textField/TextField.tsx
  src/components/accessories/textField/types.ts
  src/resources/i18n/fr.json
  src/resources/i18n/it.json
Labels: enhancement

#262 OP-813 | Implement admission section
  src/components/accessories/admission/PatientAdmission.tsx
  src/components/accessories/admission/PatientAdmissions.tsx
  src/components/activities/patientDetailsActivity/OutPatientDashboardMenu.tsx
  src/components/activities/patientDetailsActivity/PatientDetailsActivity.tsx
Labels: enhancement

#268 OP-835 | Add back the admission history to the Admission section
  src/components/accessories/admission/PatientAdmission.tsx
  src/components/accessories/admission/PatientAdmissions.tsx
  src/mockServer/fixtures/patientDTO.js
Labels: enhancement

#269 OP-836 | Enable fields in admission form
  src/components/accessories/admission/admissionForm/AdmissionForm.tsx
Labels: enhancement

#270 OP-839 | Fix wording within Admission confirmation dialog
  src/components/accessories/admission/PatientAdmission.tsx
Labels: bugfix 🔥

#272 OP-837 | Add a subtitle to the inpatient Admission section
  src/components/accessories/admission/PatientAdmissions.tsx
  src/components/accessories/admission/styles.scss
  src/resources/i18n/en.json
Labels: enhancement ✨

#271 OP-838 | Remove discharge-related fields from the Admissi…
  src/components/accessories/admission/PatientAdmission.tsx
  src/components/accessories/admission/admissionForm/AdmissionForm.tsx
  src/components/accessories/admission/admissionForm/types.ts
  src/components/accessories/admission/consts.ts
  src/components/accessories/admission/useFields.tsx
Labels: adjustment 📐

#274 OP-841 | Update the discharge menu item label
  src/resources/i18n/en.json
Labels: adjustment 📐

#275 OP-842 | Add field “note” to Discharge form
  src/components/accessories/discharge/PatientDischarge.tsx
  src/components/accessories/discharge/consts.ts
  src/components/accessories/discharge/dischargeForm/DischargeForm.tsx
  src/components/accessories/discharge/dischargeForm/types.ts
  src/components/accessories/discharge/useFields.tsx
Labels: enhancement ✨

#276 OP-843 | Set first item menu as Patient Dashboard default se…
  src/components/accessories/admission/PatientAdmission.tsx
  src/components/activities/patientDetailsActivity/InPatientDashboardMenu.tsx
  src/components/activities/patientDetailsActivity/OutPatientDashboardMenu.tsx
  src/components/activities/patientDetailsActivity/PatientDetailsActivity.tsx
  src/components/activities/searchPatientActivity/PatientSearchItem.tsx
Labels: adjustment 📐

#273 OP-840 | Update error InfoBox
  src/components/accessories/admission/PatientAdmission.tsx
  src/components/accessories/admission/admissionTable/AdmissionTable.tsx
  src/components/accessories/billTable/BillTable.tsx
  src/components/accessories/billrecords/BillRecords.tsx
  src/components/accessories/discharge/PatientDischarge.tsx
  src/components/accessories/patientExams/PatientExams.tsx
  src/components/accessories/patientExams/patientExamsTable/PatientExamsTable.tsx
  src/components/accessories/patientOPD/patientOPD.tsx
  src/components/accessories/patientOPD/patientOPDTable/PatientOPDTable.tsx
  src/components/accessories/patientPicker/PatientPicker.tsx
  src/components/accessories/patientTherapy/PatientTherapy.tsx
  src/components/accessories/patientTherapy/patientTherapyTable/PatientTherapyTable.tsx
  src/components/accessories/patientTriage/PatientTriage.tsx
  src/components/accessories/patientTriage/patientTriageTable/PatientTriageTable.tsx
  src/components/accessories/patientVisit/patientVisit.tsx
  src/components/accessories/patientVisit/patientVisitTable/PatientVisitTable.tsx
  src/components/accessories/paymentsTable/PaymentsTable.tsx
  src/components/activities/editPatientActivity/EditPatientActivity.tsx
  src/components/activities/newPatientActivity/NewPatientActivity.tsx
  src/components/activities/searchPatientActivity/SearchPatientActivity.tsx
Labels: enhancement ✨

#281 Update API specification
  api/oh.yaml
  src/generated/.openapi-generator/FILES
  src/generated/apis/AdmissionControllerApi.ts
  src/generated/apis/OperationControllerApi.ts
  src/generated/apis/OperationTypeControllerApi.ts
  src/generated/apis/VisitsControllerApi.ts
  src/generated/apis/index.ts
  src/generated/models/OperationRowDTO.ts
  src/generated/models/index.ts
Labels: dependencies

#278 OP-847 | Fix datefield validation error display
  src/components/accessories/dateField/DateField.tsx
  src/components/accessories/discharge/dischargeForm/DischargeForm.tsx
Labels: bugfix 🔥

#283 OP-851 | Align api spec file
  api/oh.yaml
  src/components/accessories/discharge/PatientDischarge.tsx
  src/components/accessories/discharge/consts.ts
  src/components/accessories/discharge/dischargeForm/DischargeForm.tsx
  src/components/accessories/discharge/dischargeForm/types.ts
  src/components/accessories/discharge/useFields.tsx
  src/components/accessories/patientExams/PatientExams.tsx
  src/generated/.openapi-generator/FILES
  src/generated/apis/AdmissionControllerApi.ts
  src/generated/apis/PatVacControllerApi.ts
  src/generated/apis/PatientControllerApi.ts
  src/generated/apis/PregnantTreatmentTypeControllerApi.ts
  src/generated/apis/PriceListControllerApi.ts
  src/generated/apis/PricesOthersControllerApi.ts
  src/generated/apis/SupplierControllerApi.ts
  src/generated/apis/VisitsControllerApi.ts
  src/generated/apis/WardControllerApi.ts
  src/generated/apis/index.ts
  src/generated/index.ts
  src/generated/models/AdmissionDTO.ts
  src/generated/models/BillDTO.ts
  src/generated/models/BillItemsDTO.ts
  src/generated/models/BillPaymentsDTO.ts
  src/generated/models/DiseaseDTO.ts
  src/generated/models/FullBillDTO.ts
  src/generated/models/LaboratoryDTO.ts
  src/generated/models/MovementWardDTO.ts
  src/generated/models/OpdDTO.ts
  src/generated/models/OperationDTO.ts
  src/generated/models/PatientVaccineDTO.ts
  src/generated/models/PregnantTreatmentTypeDTO.ts
  src/generated/models/PriceDTO.ts
  src/generated/models/PriceList.ts
  src/generated/models/PriceListDTO.ts
  src/generated/models/PricesOthersDTO.ts
  src/generated/models/TherapyDTO.ts
  src/generated/models/TherapyRowDTO.ts
  src/generated/models/VisitDTO.ts
  src/generated/models/Ward.ts
  src/generated/models/index.ts
  src/libraries/formatUtils/dataFormatting.ts
  src/resources/i18n/en.json
Labels: dependencies

#282 OP-799 | Implement operation section
  src/components/accessories/patientOperation/PatientOperation.tsx
  src/components/accessories/patientOperation/consts.ts
  src/components/accessories/patientOperation/operationForm/OperationRowForm.tsx
  src/components/accessories/patientOperation/operationForm/styles.scss
  src/components/accessories/patientOperation/operationForm/types.ts
  src/components/accessories/patientOperation/operationTable/OperationRowTable.tsx
  src/components/accessories/patientOperation/styles.scss
  src/components/accessories/patientOperation/types.ts
  src/components/activities/patientDetailsActivity/PatientDetailsActivity.tsx
  src/consts.ts
  src/index.tsx
  src/libraries/formDataHandling/functions.ts
  src/mockServer/fixtures/operationRowsDTO.js
  src/mockServer/fixtures/operationsDTO.js
  src/mockServer/routes/operations.js
  src/mockServer/server.js
  src/resources/i18n/en.json
  src/state/operations/actions.ts
  src/state/operations/consts.ts
  src/state/operations/initial.ts
  src/state/operations/reducer.ts
  src/state/operations/types.ts
  src/types.ts
Labels: enhancement ✨

#285 Update api staging3
  api/oh.yaml
  build/asset-manifest.json
  build/index.html
  build/service-worker.js
  build/static/css/main.1359cabd.chunk.css
  build/static/css/main.1359cabd.chunk.css.map
  cypress/integration/patient_details_activity/exams.spec.js
  src/components/accessories/billTable/BillTable.tsx
  src/components/accessories/billTable/RenderBillDetails.tsx
  src/components/accessories/billTable/useFormatData.tsx
  src/components/accessories/billrecords/BillRecords.tsx
  src/components/accessories/billsRecap/billsMining.ts
  src/components/accessories/discharge/PatientDischarge.tsx
  src/components/accessories/discharge/consts.ts
  src/components/accessories/discharge/dischargeForm/DischargeForm.tsx
  src/components/accessories/discharge/dischargeForm/types.ts
  src/components/accessories/patientExams/ExamForm/ExamForm.tsx
  src/components/accessories/patientExams/ExamForm/types.ts
  src/components/accessories/patientExams/PatientExams.tsx
  src/components/accessories/patientExams/consts.ts
  src/components/accessories/patientExams/patientExamsTable/PatientExamsTable.tsx
  src/components/accessories/patientNewBill/hooks/full_bill.hooks.ts
  src/generated/.openapi-generator/FILES
  src/generated/models/AdmissionDTO.ts
  src/generated/models/BillDTO.ts
  src/generated/models/FullBillDTO.ts
  src/generated/models/LaboratoryDTO.ts
  src/generated/models/PatientDTO.ts
  src/generated/models/index.ts
  src/mockServer/fixtures/billDTO.js
  src/mockServer/fixtures/laboratoryDTO.js
  src/mockServer/routes/admissions.js
  src/state/bills/actions.ts
Labels: adjustment 📐
