Repository informatici/openhospital-ui, pull requests merged in 2022-09, with the labels that each got.

#331 OH2-128 | Fix triage form and other minor bugs
  api/oh.yaml
  docker-compose.yaml
  src/components/accessories/admission/admissionForm/AdmissionForm.tsx
  src/components/accessories/laboratory/EditLaboratoryContent.tsx
  src/components/accessories/laboratory/Exams.tsx
  src/components/accessories/laboratory/LaboratoryDetails.tsx
  src/components/accessories/laboratory/consts.ts
  src/components/accessories/laboratory/filter/ExamFilterForm.tsx
  src/components/accessories/opds/filter/OpdFilterForm.tsx
  src/components/accessories/patientExams/ExamForm/ExamForm.tsx
  src/components/accessories/patientOperation/operationForm/OperationRowForm.tsx
  src/components/accessories/patientTriage/consts.ts
  src/components/accessories/patientTriage/patientTriageForm/PatientTriageForm.tsx
  src/components/accessories/patientTriage/patientTriageForm/types.ts
  src/components/accessories/patientTriage/patientTriageTable/PatientTriageTable.tsx
  src/generated/models/PatientExaminationDTO.ts
  src/libraries/formDataHandling/functions.ts
  src/resources/i18n/en.json
Labels: bugfix 🔥

#332 Implement Permission component
  src/libraries/permissionUtils/Permission.tsx
Labels: enhancement ✨

#333 OH2-130 | Update patient therapy
  src/components/accessories/admission/admissionTable/AdmissionTable.tsx
  src/components/accessories/patientExams/consts.ts
  src/components/accessories/patientOperation/consts.ts
  src/components/accessories/patientTherapy/PatientTherapy.tsx
  src/components/accessories/patientTherapy/consts.ts
  src/components/accessories/patientTherapy/therapyForm/TherapyForm.tsx
  src/components/accessories/patientTriage/patientTriageTable/PatientTriageTable.tsx
  src/generated/runtime.ts
  src/libraries/formDataHandling/functions.ts
Labels: adjustment 📐

#335 Fix permissions
  src/components/activities/patientDetailsActivity/tabsConfig.tsx
  src/mockServer/fixtures/permissionList.js
  src/types.ts
Labels: enhancement ✨
